host: "https://qa.wappsto.com"
authentication:
  username: "stefano@seluxit.com"
  password: "ciao"
iot:
  active: true
  host: qa.wappsto.com
  port: 31006
verbose: false
network:
  use_structure: true
state:
  rate: 0.1
