host: "https://dev.wappsto.com"
authentication:
  username: "stefano@seluxit.com"
  password: "ciao"
iot:
  active: true
  host: dev.wappsto.com
  port: 42006
verbose: false
network:
  use_structure: true
state:
  rate: 0.1
